// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvvLx9Wd9k3-k1U_3Vh_4QJr1_XDrMLkI',
    appId: '1:922971437681:android:4efa41981357fbf681f9d0',
    messagingSenderId: '922971437681',
    projectId: 'noook-a1f68',
    storageBucket: 'noook-a1f68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKouI2ARzHiSu0bKNCVs_5cluzbuJrNVM',
    appId: '1:922971437681:ios:45bd908ab8700c0b81f9d0',
    messagingSenderId: '922971437681',
    projectId: 'noook-a1f68',
    storageBucket: 'noook-a1f68.appspot.com',
    iosBundleId: 'com.example.noook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKouI2ARzHiSu0bKNCVs_5cluzbuJrNVM',
    appId: '1:922971437681:ios:45bd908ab8700c0b81f9d0',
    messagingSenderId: '922971437681',
    projectId: 'noook-a1f68',
    storageBucket: 'noook-a1f68.appspot.com',
    iosBundleId: 'com.example.noook',
  );
}
